---
- hosts: all
  sudo: yes
  sudo_user: isucon
  gather_facts: no
  tasks:
    - git:
        repo=https://github.com/tagomoris/xbuild.git
        dest=/home/isucon/.xbuild
        update=yes
    - command: /home/isucon/.xbuild/ruby-install -f 2.4.2 /home/isucon/local/ruby
      args:
        creates: /home/isucon/local/ruby/bin/ruby
    - command: /home/isucon/.xbuild/go-install -f 1.9 /home/isucon/local/go
      args:
        creates: /home/isucon/local/go/bin/go
